export type Business = {
  id: number;
  imageUrl: string;
  hint: string;
  name: string;
  category: string;
  rating: number;
  latitude: number;
  longitude: number;
  type: 'business' | 'service';
};

export const businesses: Business[] = [
  {
    id: 1,
    imageUrl: "https://images.unsplash.com/photo-1592861956120-e524fc739696?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxN3x8UmVzdGF1cmFudHxlbnwwfHx8fDE3NTU4NjMzNzV8MA&ixlib=rb-4.1.0&q=80&w=1080",
    hint: "cozy restaurant",
    name: "Cantina da Nona",
    category: "Restaurantes",
    rating: 4.8,
    latitude: -23.5513,
    longitude: -46.6625,
    type: 'business',
  },
  {
    id: 2,
    imageUrl: "https://images.unsplash.com/photo-1597121870960-7b5391b88b84?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyMHx8RmFybWFjaWF8ZW58MHx8fHwxNzU1ODYzNTAzfDA&ixlib=rb-4.1.0&q=80&w=1080",
    hint: "local pharmacy",
    name: "Farmácia Saúde",
    category: "Farmácias",
    rating: 4.5,
    latitude: -23.5612,
    longitude: -46.6563,
    type: 'business',
  },
  {
    id: 3,
    imageUrl: "https://placehold.co/600x400.png",
    hint: "grocery store",
    name: "Mercado do Bairro",
    category: "Mercados",
    rating: 4.3,
    latitude: -23.5478,
    longitude: -46.6459,
    type: 'business',
  },
  {
    id: 4,
    imageUrl: "https://placehold.co/600x400.png",
    hint: "modern salon",
    name: "Salão de Beleza Estilo",
    category: "Salões de Beleza",
    rating: 4.9,
    latitude: -23.558,
    longitude: -46.669,
    type: 'business',
  },
  {
    id: 5,
    imageUrl: "https://placehold.co/600x400.png",
    hint: "pet shop",
    name: "Mundo Pet",
    category: "Pet Shops",
    rating: 4.7,
    latitude: -23.549,
    longitude: -46.638,
    type: 'business',
  },
  {
    id: 6,
    imageUrl: "https://placehold.co/600x400.png",
    hint: "local gym",
    name: "Academia Corpo em Forma",
    category: "Academias",
    rating: 4.6,
    latitude: -23.563,
    longitude: -46.65,
    type: 'business',
  },
    {
    id: 7,
    imageUrl: "https://images.unsplash.com/photo-1682345262055-8f95f3c513ea?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxFbGV0cmljaXN0YXxlbnwwfHx8fDE3NTU4NjQyMzZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    hint: "man electrician",
    name: "Roberto \"Alemão\" Silva",
    category: "Eletricista",
    rating: 4.9,
    latitude: -23.555,
    longitude: -46.66,
    type: 'service',
  },
  {
    id: 8,
    imageUrl: "https://images.unsplash.com/photo-1509062522246-3755977927d7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxOHx8UHJvZmVzc29yfGVufDB8fHx8MTc1NTg2NDI5NHww&ixlib=rb-4.1.0&q=80&w=1080",
    hint: "woman tutor",
    name: "Cláudia Matos",
    category: "Aulas de Reforço (Matemática)",
    rating: 5.0,
    latitude: -23.552,
    longitude: -46.648,
    type: 'service',
  },
  {
    id: 9,
    imageUrl: "https://placehold.co/40x40.png",
    hint: "woman cleaning",
    name: "Dona Maria da Limpeza",
    category: "Serviços de Limpeza",
    rating: 4.8,
    latitude: -23.545,
    longitude: -46.655,
    type: 'service',
  },
  {
    id: 10,
    imageUrl: "https://placehold.co/40x40.png",
    hint: "man dog walker",
    name: "Fernando Passeador",
    category: "Passeador de Cães",
    rating: 4.9,
    latitude: -23.56,
    longitude: -46.64,
    type: 'service',
  },
    {
    id: 11,
    imageUrl: "https://placehold.co/40x40.png",
    hint: "man plumber",
    name: "José Encanador",
    category: "Encanador e Reparos Rápidos",
    rating: 4.7,
    latitude: -23.559,
    longitude: -46.652,
    type: 'service',
  },
    {
    id: 12,
    imageUrl: "https://placehold.co/40x40.png",
    hint: "woman seamstress",
    name: "Ateliê da Vizinhança",
    category: "Costureira - Reparos e Ajustes",
    rating: 5.0,
    latitude: -23.554,
    longitude: -46.666,
    type: 'service',
  },
];


export const classifiedAds = [
  {
    id: 1,
    imageUrl: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxCaWtlfGVufDB8fHx8MTc1NTg2NjcxN3ww&ixlib=rb-4.1.0&q=80&w=1080",
    hint: "bicycle",
    title: "Bicicleta Caloi 10, seminova",
    price: "R$ 450,00",
    seller: "João Pereira",
  },
  {
    id: 2,
    imageUrl: "https://images.unsplash.com/photo-1540574163026-643ea20ade25?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHxTb2YlQzMlQTElMjB8ZW58MHx8fHwxNzU1ODY2NzY1fDA&ixlib=rb-4.1.0&q=80&w=1080",
    hint: "sofa",
    title: "Sofá 3 lugares, bom estado",
    price: "R$ 300,00",
    seller: "Maria Oliveira",
  },
  {
    id: 3,
    imageUrl: "https://placehold.co/600x400.png",
    hint: "guitar",
    title: "Violão Giannini - Troco por teclado",
    price: "Troca",
    seller: "Pedro Martins",
  },
  {
    id: 4,
    imageUrl: "https://placehold.co/600x400.png",
    hint: "video game",
    title: "Videogame PS4 com 2 controles",
    price: "R$ 1.200,00",
    seller: "Fernanda Lima",
  },
   {
    id: 5,
    imageUrl: "https://placehold.co/600x400.png",
    hint: "baby stroller",
    title: "Carrinho de bebê",
    price: "Doação",
    seller: "Família Silva",
  },
  {
    id: 6,
    imageUrl: "https://placehold.co/600x400.png",
    hint: "books",
    title: "Coleção de livros de ficção científica",
    price: "R$ 150,00",
    seller: "Ricardo Alves",
  },
];

export const events = [
  {
    id: 1,
    imageUrl: "https://placehold.co/600x400.png",
    hint: "local fair",
    title: "Feira de Artesanato Local",
    date: "25 de Julho, 2024",
    location: "Praça da Matriz",
  },
  {
    id: 2,
    imageUrl: "https://placehold.co/600x400.png",
    hint: "live music",
    title: "Show de Rock no Coreto",
    date: "27 de Julho, 2024",
    location: "Parque Central",
  },
  {
    id: 3,
    imageUrl: "https://placehold.co/600x400.png",
    hint: "outdoor cinema",
    title: "Cinema ao Ar Livre: Clássicos dos Anos 80",
    date: "28 de Julho, 2024",
    location: "Campo de Futebol do Bairro",
  },
  {
    id: 4,
    imageUrl: "https://placehold.co/600x400.png",
    hint: "food festival",
    title: "Festival Gastronômico de Inverno",
    date: "02 de Agosto, 2024",
    location: "Rua Gastronômica",
  },
];
